// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnJk7zcuKzuMO8W7N6QRaICmI9XLD-9is',
    appId: '1:236724331491:web:55353167d05eeb721bb6d6',
    messagingSenderId: '236724331491',
    projectId: 'shoppingcartibr',
    authDomain: 'shoppingcartibr.firebaseapp.com',
    storageBucket: 'shoppingcartibr.appspot.com',
    measurementId: 'G-K4MTR2E2XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkV_Ij8Lv80Tdf1zTbQArqEX-6aenz0vw',
    appId: '1:236724331491:android:ad516dc7ef17f5e21bb6d6',
    messagingSenderId: '236724331491',
    projectId: 'shoppingcartibr',
    storageBucket: 'shoppingcartibr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbIIhzvHSaYqzu7L4hpA7Z89xdNExkBKw',
    appId: '1:236724331491:ios:5e0a243b420464be1bb6d6',
    messagingSenderId: '236724331491',
    projectId: 'shoppingcartibr',
    storageBucket: 'shoppingcartibr.appspot.com',
    iosClientId: '236724331491-0ago1b1i7636uatrq0vha2h4d4dr3pp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbIIhzvHSaYqzu7L4hpA7Z89xdNExkBKw',
    appId: '1:236724331491:ios:5e0a243b420464be1bb6d6',
    messagingSenderId: '236724331491',
    projectId: 'shoppingcartibr',
    storageBucket: 'shoppingcartibr.appspot.com',
    iosClientId: '236724331491-0ago1b1i7636uatrq0vha2h4d4dr3pp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoppingCart',
  );
}
